---
title: "Portfoltio Self Esteem"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: flatly
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(DT)

data_df <- read.csv('data.csv')

```

Abstract {.sidebar}
=====================================================

Spotify results
======================================================

Big visualization{.tabset}
--------------------------------------------------------

### RSE and danceability

```{r}

dancingscore <- ggplot(data_df, aes(x = data_df$dance, y = data_df$rse_score)) + 
  geom_point() +
  ggtitle('Comparing danceability versus RSE score') +
  xlim(c(0,1)) +
  ylim(c(0,30)) + 
  ylab('RSE Score') +
  xlab('Danceability') +
  theme_minimal()
  
ggplotly(dancingscore)

```

### RSE and energylevel

```{r}
energyscore <- ggplot(data_df, aes(x = data_df$energy, y = data_df$rse_score)) + 
  geom_point() +
  ggtitle('Comparing energylevel versus RSE score') +
  xlim(c(0,1)) +
  ylim(c(0,30)) + 
  ylab('RSE Score') +
  xlab('Energylevel') +
  theme_minimal()
  
ggplotly(energyscore)

```

### RSE and valence

```{r}
valencescore <- ggplot(data_df, aes(x = data_df$valence, y = data_df$rse_score)) + 
  geom_point() +
  ggtitle('Comparing valence versus RSE score') +
  ylab('RSE Score') +
  xlim(c(0,1)) +
  ylim(c(0,30)) + 
  xlab('Valence') +
  theme_minimal()
  
ggplotly(valencescore)

```

### RSE and mode

```{r}
modescore <- ggplot(data_df, aes(x = data_df$mode, y = data_df$rse_score)) + 
  geom_point() +
  ggtitle('Comparing mode versus RSE score') +
  xlim(c(0,1)) +
  ylim(c(0,30)) + 
  ylab('RSE Score') +
  xlab('Mode') +
  theme_minimal()
  
ggplotly(modescore)

```

Demographic results
========================================================

Column
---------------------------------------------------------

### Visualization

```{r}


```

Background{data-navmenu="Research"}
========================================================

Column
-------------------------------------------------------

### Chart A

```{r}

```

References{data-navmenu="Research"}
=========================================================

Column
-------------------------------------------------------

### Chart B

```{r}

```

